/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c2a25905-8075-4492-a926-88ac74dd3d72",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Jw0wmY7M9",
    "aws_user_pools_web_client_id": "30mqr0nbj9m25iq5j6maiuq8f0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dayqhfolbrhjfavny6r2xj5vp4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-72ubv5avwff4pipdua2wnjdyzu",
    "aws_user_files_s3_bucket": "profileappbucket111336-develop",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
